### ISSUE TITLE
Hablar de herramientas existentes

### ISSUE THREAD

**Issue by unintendedbear** [unintendedbear/Plan-de-investicaci-n-t-sis#10]
¿En profundidad? ¿Por encima como en el artículo del GECCO?

**Comment by fergunet** [comment]
Por encima. Un par de frases como mucho.

**Comment by fergunet** [comment]
Por cierto, creo que hay un limite de palabras, preguntale a @deantares

**Comment by deantares** [comment]
En el plan de investigación creo que no. Es en el informe anual en donde me han dicho que hay una limitación de 400 palabras por apartado.

**Comment by JJ** [comment]
Por encima.
