### ISSUE TITLE
Generalizar un poco más la tesis

### ISSUE THREAD

**Issue by JJ** [unintendedbear/Plan-de-investicaci-n-t-sis#11]
Me da la impresión de que se está concentrando demasiado en Muses, con todo lo que ello conlleva, incluyendo que el proyecto acaba en 15 días. Tendríamos que pensar en qué contexto más general está y, realmente, cuál es "la tesis", qué hipótesis podemos probar y demás.

**Comment by unintendedbear** [comment]
Vale, si llevas razón, pero no sé muy bien cómo generalizar :(
¿Qué opinas tú también @fergunet ?

**Comment by fergunet** [comment]
A ver, creo que lo primero es definir la pregunta a responder:
_¿Es posible utilizar métodos de Machine Learning para detectar amenazas o vulnerabilidades en sistemas BYOD de forma dinámica?_ (Si esta no es la pregunta correcta, corregidla en otro comentario abajo, pero vamos a empezar por ahí.)

La respuesta a la pregunta, es "SÍ, claro". Lo que nos lleva a la siguiente pregunta. _¿Cómo podemos demostrar que se pueden usar algoritmos de ML para detectar amenazas o vulnerabilidades de forma dinámica?_ Pues creando varios algoritmos que lo hagan, por ejemplo, usando PG o clustering, etc. Esto es un poco tautología y sé que a @JJ no le va a molar, pido perdón de antemano, pero es que no se me ocurre como escribirlo.

_¿Cómo lo vamos a hacer?_ Proponemos una metodología consistente en 
1) Proponer métrica de detección de vulnerabilidades/ataques (por ejemplo, número de vulnerabilidades detectadas, número de reglas generadas, lo que sea) 
2) Generar un benchmark de casos de usos
3) Comparar distintos algoritmos respecto a esa métrica 

¿Es más o menos la idea de la tesis?

**Comment by unintendedbear** [comment]
Me gustaría saber por qué no me llegan al email vuestros comentarios ni nada :\

Estoy de acuerdo con todo, ¿añadimos ML al título?
¿En el punto 1 se puede poner que es importante para obtener una buena función de fitness?
Como objetivos teníamos:

1 - Definir qué métricas son más interesantes.
2 - Comparar qué técnicas de Soft Computing son más adecuadas para un entorno como este.
3 - Desarrollar una metodología (que se pueda vender a la gente) compuesta de varios pasos:
     3.1 - Pre-procesamiento de datos
     3.2 - Ejecución, comparativa y análisis
     3.3 - Validación de los resultados

¿Meto el benchmark dentro de la metodología que queremos proponer?
Lo que ya no sé es cómo definir los mini-objetivos para hacerme el planning. Realmente es lo único que me falta.

**Comment by fergunet** [comment]
Sí, el benchmark debería estar en la metodología, ya que lo vas a usar en ella.

Posibles miniobjetivos (puestos con X.minúscula), mira a ver si tienen sentido.

1 - Definir qué métricas son más interesantes.
1.a. Estudio del arte en sistemas BYOD (lo de la revista)
2.a. Comparativa de métricas usadas en la literatura: usos, ventajas e inconvenientes de cada una
3.b. Justificación de la métrica escogida.
2 - Comparar qué técnicas de Soft Computing son más adecuadas para un entorno como este.
2.a. Estudio del arte en técnicas Soft Computing aplicadas a BYOD. (Relacionado con el sub-objetivo del punto 1.a)
2.b. Relación entre la métrica escogida en el punto anterior con las técnicas anteriores.
2.c. Justificación de las técnicas escogidas respecto a la métrica(s).
3 - Desarrollar una metodología (que se pueda vender a la gente) compuesta de varios pasos:
3.a. Creación de un benchmark para experimentación.
3.1 - Pre-procesamiento de datos
3.b. Justificación de la(s) técnica(s) de procesamiento
3.2 - Ejecución, comparativa y análisis
3.c. (aquí no sé qué sub-objetivo poner xD)
3.3 - Validación de los resultados
3.d. Definir cómo se validan esos resultados: comparando las métricas de cada técnica entre sí, extrayendo conocimiento a partir de los datos.

**Comment by unintendedbear** [comment]
Ok, todo chachi, pero me lío en el último punto por cómo he numerado yo y luego tú.

Creo que por un lado, deberíamos poner "Desarrollar una metodología (que se pueda vender a la gente) compuesta de varios pasos:
- Paso 1, un preprocesamiento de datos de X forma
- Paso 2, un entorno de ejecución
- Paso 3, cómo analizar los resultados"

Y ahoooora: "Para ello, necesitamos los siguientes subobjetivos:
- Benchmark
- Elección de técnica de preprocesamiento y justificación
- Técnicas de procesamiento a aplicar y cómo
- Definir cómo se validan esos resultados: comparando las métricas de cada técnica entre sí, extrayendo conocimiento a partir de los datos."

Mola o no mola?

**Comment by fergunet** [comment]
Exacto, es que los he metido en mitad para ver a qué parte de la metodología afectaban, pero mejor por separado, como has hecho tú, que si no es un lío. O para completarlo del todo:

Benchmark (afecta al paso 1 y 2)
Elección de técnica de preprocesamiento y justificación (afecta al paso 1)
Técnicas de procesamiento a aplicar y cómo (afecta al paso 2)
Definir cómo se validan esos resultados: comparando las métricas de cada técnica entre sí, extrayendo conocimiento a partir de los datos. (afecta al paso 3)

**Comment by unintendedbear** [comment]
Ok, pues ahora lo acabo

**Comment by unintendedbear** [comment]
Tengo una duda, y es que no he puesto nada de estudiar los algoritmos evolutivos en reglas en los objetivos, aunque sí que lo cité en la hipótesis :(

**Comment by fergunet** [comment]
Quita entonces lo de AEs en la hipótesis y pon "técnicas de Machine Learning", así en general. Puedes poner si quieres "como por ejemplo, los AEs o los Whatevers"

**Comment by unintendedbear** [comment]
oh, ok :( lo siento >_< perdonad la ignorancia, me da vergüenza y todo

**Comment by fergunet** [comment]
Meh, yo aprendí todas estas movidas de las hipótesis y objetivos una semana antes de entregar la tesis xD (y toavía no lo tengo claro... :P )
